const events = {
    ABOUT_FOODFLICK: 'ABOUT_FOOD_FLICK',
    PROFILE: 'PROFILE',
    LOGO: 'LOGO',
    CLOSE_SEARCH: 'CLOSE_SEARCH',
    REVIEW_CART: 'REVIEW_CART',
    PLACE_ORDER: 'PLACE_ORDER',
    CART: 'CART',
    SEARCH_BAR: 'SEARCH_BAR',
    SEARCH_BAR_ITEM: 'SEARCH_BAR_ITEM',

}

export default events;