const events = {
    ABOUT_FOODFLICK: 'ABOUT_FOOD_FLICK',
    SIGN_UP: 'SIGN_UP',
    SIGN_IN: 'SIGN_IN',
    LOGIN_WITH_REFRESH: 'LOGGED IN WITH REFRESH',
    PROFILE: 'PROFILE',
    LOGO: 'LOGO',
    CLOSE_SEARCH: 'CLOSED SEARCH BAR',
    REVIEW_CART: 'REVIEW_CART',
    PLACE_ORDER: 'PLACE_ORDER',
    CART: 'CHECKED CART',
    SEARCH_BAR: 'SEARCH_BAR',
    SEARCH_BAR_ITEM: 'SEARCH_BAR_ITEM',


}

export default events;