mutation addItems($restId: ID!, $categoryName: String!, $items: [NewItemInput!]!) {
  addItems(restId: $restId, categoryName: $categoryName, items: $items) {
    ...restFragment
  }
}
        
fragment restFragment on Rest {
  _id
  profile {
    name
    phone
    description
  }
  location {
    address {
      address1
      address2
      city
      state
      zip
    }
  }
  owner {
    userId
    email
  }
  managers {
    userId
    email
  }
  menu {
    name
    description
    items {
      name
      prices {
        value
        label
      }
      printers {
        name
        ip
        port
        type
      }
      description
      flick
    }
  }
}

{
  "restId": "D71rFmwB0QaGhfaOS2Jp",
  "categoryName": "Noodles",
  "items": [
    {
      "name": "printer test",
      "prices": [
        {
          "value": 4
        }
      ],
      "optionGroups": [],
      "printers": []
    }
  ]
}