mutation addRestPrinter($restId: ID!, $newPrinter: PrinterInput!) {
  addRestPrinter(restId: $restId, newPrinter:$newPrinter) {
    ...restFragment
  }
}

fragment restFragment on Rest {
  _id
  profile {
    name
    phone
    description
  }
  location{
    address {
      address1
      address2
      city
      state
      zip
    }    
  }
  owner {
    userId
    email
  }
  managers {
    userId
    email
  }
  printers {
    name
    ip
    port
    type
  }
  menu {
    name
    description
    items {
      name
      prices {
       value
        label
      }
      printers {
        name
        ip
        port
        type
      }
      description
      flick
    }
  }
}
