mutation updateRestAddress($restId: ID!, $newAddress: AddressInput!) {
  updateRestAddress(restId: $restId, newAddress: $newAddress) {
    ...restFragment
  }
}
        
fragment restFragment on Rest {
  _id
  profile {
    name
    phone
    description
  }
  address {
    address1
    address2
    city
    state
    zip
  }
  owner {
    _id
    email
  }
  managers {
    _id
    email
  }
  menu {
    name
    description
    items {
      name
      price
      description
      flick
    }
  }
}
